
ShulkerBox-setting:
  # 设置冷却 [ 单位 秒 ]
  cooldown:
    on-open: 5
    message: '&7[&3MagiciteCore&7] 请勿频繁操作潜影盒...'

# 数据库配置
database-setting:
  enable: false
  host: localhost
  port: 3306
  user: root
  password: 12345
  database: minecraft
  table-prefix: 'magicite_core'